### ISSUE TITLE
Can this app be compiled on Linux?

### ISSUE THREAD

**Issue by eggice1234** [jason53415/blockly-app#1]
Hi Jason,
My OS is Manjaro Linux. 
While following the instruction to build from source, an error happened in this step - npm run make-py.
Not sure if Linux is supported since only Windows/Mac binaries were provided.
I have little knowledge to debug. If it's not trivial to deal with, I would boot to my slow win7 anyway.
Any suggesiton? Thanks.
eggice

=========================================================
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/eggice/.local/lib/python3.9/site-packages/PyInstaller/hooks/hook-gi.repository.Gdk.py", line 16, in <module>
    binaries, datas, hiddenimports = get_gi_typelibs('Gdk', '3.0')
  File "/home/eggice/.local/lib/python3.9/site-packages/PyInstaller/utils/hooks/gi.py", line 90, in get_gi_typelibs
    path = findSystemLibrary(lib.strip())
  File "/home/eggice/.local/lib/python3.9/site-packages/PyInstaller/depend/bindepend.py", line 958, in findSystemLibrary
    return findLibrary(name)
  File "/home/eggice/.local/lib/python3.9/site-packages/PyInstaller/depend/bindepend.py", line 774, in findLibrary
    utils.load_ldconfig_cache()
  File "/home/eggice/.local/lib/python3.9/site-packages/PyInstaller/depend/utils.py", line 402, in load_ldconfig_cache
    path = m.groups()[-1]
AttributeError: 'NoneType' object has no attribute 'groups'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blockly-app@1.2.0 make-py: `cd ./python && pyinstaller -y --hidden-import=pathlib --hidden-import=matplotlib.pyplot --hidden-import=pynput.keyboard._win32 --hidden-import=pynput.mouse._win32 --hidden-import=pynput.keyboard._darwin --hidden-import=pynput.mouse._darwin --hidden-import=queue --hidden-import=pygame --hidden-import=multiprocessing --hidden-import=pickle --hidden-import=Box2D --hidden-import=sklearn.neighbors --hidden-import=sklearn.tree --hidden-import=sklearn.svm --hidden-import=sklearn.ensemble --hidden-import=sklearn.neural_network --hidden-import=sklearn.metrics --hidden-import=sklearn.utils._weight_vector --hidden-import=scipy.special.cython_special interpreter.py`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blockly-app@1.2.0 make-py script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/eggice/.npm/_logs/2021-07-03T14_37_46_405Z-debug.log
[eggice@eggice-inspiron3543 blockly-app]$ gvim /home/eggice/.npm/_logs/2021-07-03T14_37_46_405Z-debug.log

**Comment by jason53415** [comment]
It seems to be the same issue as https://github.com/pyinstaller/pyinstaller/issues/5540.
Upgrading PyInstaller to 4.3 should help.

**Comment by eggice1234** [comment]
Thanks.
After I upgraded PyInstaller to 4.3, I can move on to next step and generate executable.
Although still have trouble building deb/rpm, I can run blockly-app in linux now.

**Comment by eggice1234** [comment]
![blockly-app](https://user-images.githubusercontent.com/86884287/127025572-23edc52d-82a0-48d3-bbea-552cba0defe9.png)
